language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- python setup.py install
- pip install keras
- pip install codecov
script:
- coverage run tests/test_keras_example.py
after_success:
- codecov
deploy:
  provider: pypi
  user: paramount_east
  password:
    secure: cNnt596kls29fB1X7xkwI8XH+GCECZoMebkVoOsI8V+Oj1rr8DKN3cvzYsFja96O92G+xflgNPQ11gFEtM5F+2v0XplPH/lLyOG3Ma8GVUpFBk27kfGL3wLLynGiBVG+R7BzhQh86fOZ214qMzupsNZ3D7zAfBs+dDgcV9WF/4DKJdNMPOnKBSunJt84ydlkhxJyIjpWCiSm3s6PdaySg4DwVnlICDsxbFNhyhz5yxsINO6ATFXhBJ98hGR85u9yJStpLd5hLV33Dk5VsBhxagytV4OhlQU96ga7xNK/YcWdDO4F0bFVP3zfIc7cpOYl71Li6WycNX+Rz2LP8iwakFlM1CMrUR6ahGntik64Z+xr5nE/8DEzRKBdZ9T6W9QgUGDtfyR9XDFRSh5FpTZc9JqqWJuOTlhDrYXNxiRnOimj/2XD3EnJyNpCq43vxrLOPHNhKYIetvVFNcfiWBSCnVaXymS/FeG9MYheg3C66oVKvbqGYH4GZhj4i/R836VP+T1ya9a91NOj4wwchaFtnqEayfw53qeftAEI8piZX+ly6eUANlwQfL3tgNbu/xhguDuAu3b6L9wFnOKT6GJi1hw+XJltUZYYBQbF1myVrdD+pQFSZjgL6wffUShQqQWztm94+8OVLA0mmEr66hJrIq5ImJfnZ6d0bomtvqGG0tI=
