language: python
python:
- '3.6'
install:
- pip install -q -r requirements.txt
- pip install -q codecov
- pip install .
- python setup.py sdist bdist_wheel
script:
- coverage run tests/test_keras_example.py
after_success:
- codecov
deploy:
  provider: pypi
  user: paramount_east
  password:
    secure: FfOgnjwJtg8EYE3v/bAL3XHwbTmS4kR3PC29SEJ/s7plKuJvDD3w9exAGRuvcS8uPgntEFnm/MGvflOFXXivv/ZmJbaYGihs8oOrZEElc9iatpOlrcYqFVNwxE4U26IS0pqZpMJl1XMP+PTe0VjtfEBwiJMT4TNEYeTKG1F6s6NaslvNIEra2g7d6Tyox2KRFobFo4Cot66zJ0cE9Lrzp7AqtgSAhiqr0Ma8/b6hE/It77kj1Jh60zSEMbn0S38Ttt9MBl+WzH9nH2VY40ecNzLL2F3IWnaXyD54TjZveb/1QtGZzsRghKrTLeo4NG9J0tZgSn/xttS+LPy5KvbaGwOQNQRUc3caCsmp6Lr1e2rfFBPJHQ1cQhlLOoRsejBG47kJWTZqjem2hHlZyKRoOx747uLTDGyjZzRcwtwO95JK1K8qURXHR7fVBu3N1BZt4XnTPUAGuM3lJ75KvND9sBbt9P7ah/twLCU0VqakG45jt7TEpR2m1+kMMQ03Gm6gIEYk5b6B+zYgqt6RFB8XrHyKEQmRZhZd/CoAOTzvIAgOqxLgaFPlKMfun+L5k1Lq8DhN2+zXo/IHZMTskHSA0QlpEeBjNm14Ey+pt5O/jk1w+2Ly0QMpepWKtSQOXCl48sCFyNHeT9I/m5pi40fp6V639Spmrd6cXOyFID3aDc8=
  on:
    branch: release